### PR TITLE
Issue #84 - Add SLE parameters to config file

### PR DESCRIPTION
**Pull request by Futabay**
SLE parameters were added to `config.yaml` and `rcf.py`, `raf.py` and `cltu.py` were updated accordingly.
FYI, I set all protocols `version` to 4 as a default. Please let me know if I should set `rcf` and `cltu` `version` to 5.

### CODE REVIEW

**Comment by aywaldron** [comment]
Hi @Futabay , thanks for the PR! This looks good. I just noticed in reviewing the code, however, that `auth_level` is being picked up in [common.py](https://github.com/NASA-AMMOS/AIT-DSN/blob/9a266b023368695fb540a598d8d44f88de222a8e/ait/dsn/sle/common.py#L119) before the cltu/rcf/raf classes. Also, the required default should be `"none"` rather than `None`:
https://github.com/NASA-AMMOS/AIT-DSN/blob/9a266b023368695fb540a598d8d44f88de222a8e/ait/dsn/sle/common.py#L129

Can we change setting the `auth_level`s to default to the already set `self._auth_level`? Then that will already have the appropriate `"none"` default if not specified under `dsn.sle.auth_level`.

Thanks!

**Comment by MJJoyce** [comment]
Sorry to jump on this ticket late and (potentially) ask for a change.

```
self._auth_level = ait.config.get('dsn.sle.fcltu.auth_level',
                                          kwargs.get('auth_level', self._auth_level))
```

I think the current config grabs is prioritizing settings differently than we'd like.

I think we'd like the priority to be:
```
Constructor kwargs > SLE specific auth level > global auth level
```

It looks like with the current code we're getting
```
SLE specific auth level > Constructor kwargs > global auth level
```

Thoughts on changing that priority around?

**Comment by aywaldron** [comment]
@MJJoyce I agree that switching the priority may be a good idea, yes. The current priority implemented is based on what was already there before working on this ticket, e.g. [here](https://github.com/NASA-AMMOS/AIT-DSN/blob/ebd1db5708be11c2aceb45caad833bd7d1d57529/ait/dsn/sle/cltu.py#L105), so would require changes beyond this ticket for consistency.

**Comment by MJJoyce** [comment]
+1, I'm good with that then. Let's just make sure we open up a follow up when we close this out and get the ordering changed.

**Comment by aywaldron** [comment]
Opened ticket https://github.com/NASA-AMMOS/AIT-DSN/issues/95 for this and approving & merging this PR.

**Pull request merged**
